### ISSUE TITLE
Schedule automatic deployment when we move to Heroku

### ISSUE THREAD

**Issue by iampava** [FrontEnd-ro/frontend.ro#73]
```
name: Deploy
on:
  schedule:
  - cron: '0 12,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "yourAppName"
          heroku_email: "email@email.com"
          branch: "master"
```

Sample code courtesy  of https://github.com/nmaties/. This is for 2 deployes per day
